name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # uses lean standard action
      - uses: austinletson/lean-standard-action@develop
        with:
          # run lake test
          test: true
