name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lean-workflow:
    uses: austinletson/lean-standard-action/.github/workflows/ci.yml@develop
    # runs-on: ubuntu-latest

    # steps:
    #   # uses lean standard action with all default input values
    #   - uses: austinletson/lean-standard-action@develop
    #     with:
    #       check-reservoir-eligibility: true
